"""Download the site's web fonts once, so pages never load anything from Google.

Loading fonts from Google's servers sends every visitor's IP address to Google, which German
courts have held to need consent under the GDPR. Self-hosting avoids that. All three families
are under the SIL Open Font License, which allows redistribution; the licence texts are saved
next to the fonts.

    uv run python scripts/fetch_fonts.py
"""

import re
import urllib.request
from pathlib import Path

FONTS = Path(__file__).resolve().parent.parent / "static" / "fonts"
CSS_URL = (
    "https://fonts.googleapis.com/css2?family=Geist:wght@300..700"
    "&family=Geist+Mono:wght@400..600&family=Instrument+Serif:ital@0;1&display=swap"
)
SUBSETS = ("latin", "latin-ext")  # enough for English and Spanish
LICENCES = {
    "OFL-Geist.txt": "https://raw.githubusercontent.com/google/fonts/main/ofl/geist/OFL.txt",
    "OFL-GeistMono.txt": "https://raw.githubusercontent.com/google/fonts/main/ofl/geistmono/OFL.txt",
    "OFL-InstrumentSerif.txt": "https://raw.githubusercontent.com/google/fonts/main/ofl/instrumentserif/OFL.txt",
}
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/130.0 Safari/537.36"


def get(url: str) -> bytes:
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA})) as r:
        return r.read()


def main() -> None:
    FONTS.mkdir(parents=True, exist_ok=True)
    css = get(CSS_URL).decode()
    out = ["/* Self-hosted web fonts (SIL Open Font License). Generated by scripts/fetch_fonts.py */"]
    for subset, block in re.findall(r"/\* ([a-z0-9-]+) \*/\s*(@font-face \{.*?\})", css, re.S):
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        style = re.search(r"font-style: (\w+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        name = f"{family.lower().replace(' ', '-')}-{style}-{subset}.woff2"
        (FONTS / name).write_bytes(get(url))
        out.append(block.replace(url, f"/static/fonts/{name}"))
        print("saved", name)
    (FONTS / "fonts.css").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    for name, url in LICENCES.items():
        (FONTS / name).write_bytes(get(url))
        print("saved", name)


if __name__ == "__main__":
    main()
